name: oryn
description: A truth-resolution protocol where claims exist only while continuously proven.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Data Modeling
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  uuid: ^4.2.1
  path_provider: ^2.1.1
  intl: ^0.18.1
  freezed: ^2.5.2
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true